config/routes.rb
Rails.application.routes.draw do
  resources :select_options

  resources :tables do
    resources :columns
    resources :rows
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/select_option.rb
class SelectOption < ApplicationRecord
  belongs_to :column
end

app/controllers/select_options_controller.rb
class SelectOptionsController < ApplicationController
  before_action :set_select_option, only: %i[ show edit update destroy ]

  # GET /select_options or /select_options.json
  def index
    @select_options = SelectOption.all
  end

  # GET /select_options/1 or /select_options/1.json
  def show
  end

  # GET /select_options/new
  def new
    @select_option = SelectOption.new
  end

  # GET /select_options/1/edit
  def edit
  end

  # POST /select_options or /select_options.json
  def create
    @select_option = SelectOption.new(select_option_params)

    respond_to do |format|
      if @select_option.save
        format.html { redirect_to select_option_url(@select_option), notice: "Select option was successfully created." }
        format.json { render :show, status: :created, location: @select_option }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @select_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /select_options/1 or /select_options/1.json
  def update
    respond_to do |format|
      if @select_option.update(select_option_params)
        format.html { redirect_to select_option_url(@select_option), notice: "Select option was successfully updated." }
        format.json { render :show, status: :ok, location: @select_option }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @select_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /select_options/1 or /select_options/1.json
  def destroy
    @select_option.destroy

    respond_to do |format|
      format.html { redirect_to select_options_url, notice: "Select option was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_select_option
      @select_option = SelectOption.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def select_option_params
      params.require(:select_option).permit(:column_id, :text)
    end
end

app/helpers/select_options_helper.rb
module SelectOptionsHelper
end

app/views/select_options/_form.html.erb
<%= form_with(model: select_option) do |form| %>
  <% if select_option.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(select_option.errors.count, "error") %> prohibited this select_option from being saved:</h2>

      <ul>
        <% select_option.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :column_id, style: "display: block" %>
    <%= form.text_field :column_id %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/select_options/_select_option.html.erb
<div id="<%= dom_id select_option %>">
  <p>
    <strong>Column:</strong>
    <%= select_option.column_id %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= select_option.text %>
  </p>

</div>

app/views/select_options/edit.html.erb
<h1>Editing select option</h1>

<%= render "form", select_option: @select_option %>

<br>

<div>
  <%= link_to "Show this select option", @select_option %> |
  <%= link_to "Back to select options", select_options_path %>
</div>

app/views/select_options/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Select options</h1>

<div id="select_options">
  <% @select_options.each do |select_option| %>
    <%= render select_option %>
    <p>
      <%= link_to "Show this select option", select_option %>
    </p>
  <% end %>
</div>

<%= link_to "New select option", new_select_option_path %>

app/views/select_options/new.html.erb
<h1>New select option</h1>

<%= render "form", select_option: @select_option %>

<br>

<div>
  <%= link_to "Back to select options", select_options_path %>
</div>

app/views/select_options/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @select_option %>

<div>
  <%= link_to "Edit this select option", edit_select_option_path(@select_option) %> |
  <%= link_to "Back to select options", select_options_path %>

  <%= button_to "Destroy this select option", @select_option, method: :delete %>
</div>