config/routes.rb
Rails.application.routes.draw do
  resources :select_options

  resources :tables do
    resources :columns
    resources :rows
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/column.rb
class Column < ApplicationRecord
  self.inheritance_column = :_type_disabled
  belongs_to :table
  has_many :select_options, dependent: :destroy

  before_create :generate_code

  enum type: {
    single_select: 'single_select',
    single_line_text: 'single_line_text',
    date: 'date',
    number: 'number',
    formula: 'formula',
  }

  private

  def generate_code
    the_code = Nanoid.generate(size: 10, alphabet: '0123456789abcdefghijklmnopqrstuvwxyz')
    self.code = "col#{the_code}"
  end
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  before_action :set_table
  before_action :set_column, only: %i[ show edit update destroy ]

  # GET /columns or /columns.json
  def index
    @columns = Column.all
  end

  # GET /columns/1 or /columns/1.json
  def show
  end

  # GET /columns/new
  def new
    @column = @table.columns.new
  end

  # GET /columns/1/edit
  def edit
  end

  # POST /columns or /columns.json
  def create
    @column = @table.columns.new(column_params)

    respond_to do |format|
      if @column.save
        format.html { redirect_to table_url(@table), notice: "Column was successfully created." }
        format.json { render :show, status: :created, location: @column }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @column.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /columns/1 or /columns/1.json
  def update
    respond_to do |format|
      if @column.update(column_params)
        format.html { redirect_to table_url(@table), notice: "Column was successfully updated." }
        format.json { render :show, status: :ok, location: @column }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @column.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /columns/1 or /columns/1.json
  def destroy
    @column.destroy

    respond_to do |format|
      format.html { redirect_to table_url(@table), notice: "Column was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_column
      @column = @table.columns.find(params[:id])
    end

    def set_table
      @table = Table.find(params[:table_id])
    end

    # Only allow a list of trusted parameters through.
    def column_params
      params.require(:column).permit(:table_id, :name, :code, :type, :setting)
    end
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/views/columns/_column.html.erb
<tr id="<%= dom_id column %>">

<td>
    <%= link_to column.id, edit_table_column_path(@table, column) %>
  </td>

  <td>
    <%= column.name %>
  </td>

  <td>
    <%= column.code %>
  </td>

  <td>
    <%= column.type %>
  </td>

  <td>
    <%= button_to "Delete", table_column_path(@table, column), method: :delete %>
  </td>

  <td>
    <%= column.select_options.map(&:text) if column.type == "single_select" %>
    <%= column.setting if column.type == "formula" %>
  </td>


</tr>

app/views/columns/_form.html.erb
<%= form_with(model: [@table, column]) do |form| %>
  <% if column.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(column.errors.count, "error") %> prohibited this column from being saved:</h2>

      <ul>
        <% column.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= @table.name %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.select :type, options_for_select(Column.types.values, selected: column.type) %>
  </div>

  <div>
    <%= form.label :setting, style: "display: block" %>
    <%= form.text_field :setting %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/columns/edit.html.erb
<h1>Editing column</h1>

<%= render "form", column: @column %>

<br>

<div>
  <%= link_to "Back to columns", table_columns_path(@table) %>
</div>

app/views/columns/index.html.erb
<p style="color: green"><%= notice %></p>

<%= render @table %>

<table>
  <tr>
    <th>Name</th>
    <th>Code</th>
    <th>Type</th>
  </tr>
  <%= render @table.columns %>
</table>

<%= link_to "New column", new_table_column_path(@table) %>

app/views/columns/new.html.erb
<h1>New column</h1>

<%= render "form", column: @column %>

<br>

<div>
  <%= link_to "Back to table", @table %>
</div>

app/views/columns/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @column %>

<div>
  <%= link_to "Edit this column", edit_column_path(@column) %> |
  <%= link_to "Back to columns", columns_path %>

  <%= button_to "Destroy this column", @column, method: :delete %>
</div>