config/routes.rb
Rails.application.routes.draw do
  resources :select_options

  resources :tables do
    resources :columns
    resources :rows
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/tables_controller.rb
require "dentaku"
require 'dentaku/parser'

FUNCTION_MAPPING = {
  'right' => 'right',
  'left' => 'left',
}


def translate_function_to_sql(formula)

  # Parse the formula into an AST
  tokens = Dentaku::Tokenizer.new.tokenize(formula)
  ast = Dentaku::Parser.new(tokens).parse

  # Walk the AST and translate it into SQL
  sql = ast_node_to_sql(ast)

  puts sql

  # Wrap the translated formula in a SELECT statement
  "#{sql}"
end

def ast_node_to_sql(node)
  if node.is_a?(Dentaku::AST::Function)
    sql_func_name = FUNCTION_MAPPING[node.name] || node.name
    "#{sql_func_name}(#{node.args.map{|a| ast_node_to_sql(a)}.join(',')})"
  elsif node.is_a?(Dentaku::AST::Arithmetic)
    " #{node.operator} "
  elsif node.is_a?(Dentaku::AST::Node)
    "#{node.value}"
  else
    node.value.to_s
  end

end


class TablesController < ApplicationController
  before_action :set_table, only: %i[ show edit update destroy ]

  # GET /tables or /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1 or /tables/1.json
  def show


    @select_options = SelectOption.where(column_id: @table.columns.pluck(:id))
    # convert @select_options to hash
    @select_options_hash = {}
    @select_options.each do |select_option|
      @select_options_hash[select_option.id] = select_option.text
    end

    columnMap = {}
    @table.columns.each do |column|
      columnMap[column.name] = column
    end

    select_values = @table.columns.map do |column|
      if column.type == "formula"
        f_str = column.setting # "{Unit Sold} * ({Unit Price} - {Unit Cost})"

        columnMap.each do |cname, col|
          if col.type == "number"
            f_str.gsub! "{#{cname}}", "cast(values -> '#{col.code}' AS decimal)"
          elsif col.type == "formula"
            f_str.gsub! "{#{cname}}", "cast(values -> '#{col.code}' AS decimal)"
          else
            f_str.gsub! "{#{cname}}", "cast(values ->> '#{col.code}' AS text)"
          end
        end
        "#{f_str} AS values_#{column.code}"
      else
        "values -> '#{column.code}' AS values_#{column.code}"
      end
    end

    @rows = @table.rows.select([:id].concat(select_values)).page(params[:page]).per(100).order(:id)

  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables or /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to table_url(@table), notice: "Table was successfully created." }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1 or /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to table_url(@table), notice: "Table was successfully updated." }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1 or /tables/1.json
  def destroy
    @table.destroy

    respond_to do |format|
      format.html { redirect_to tables_url, notice: "Table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def table_params
      params.require(:table).permit(:name)
    end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.erb
<%= form_with(model: table) do |form| %>
  <% if table.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
        <% table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tables/_row_header.html.erb
<tr>
  <th>#</th>
  <% columns.each do |c|%>
  <th><%= c.name %>
    <%= link_to "E", edit_table_column_path(@table, c)%>
  </th>
  <% end %>
</tr>

app/views/tables/_table.html.erb
<div id="<%= dom_id table %>">
  <p>
    <%= link_to table.name, @table %>
  </p>

  <p>
    <%= link_to "Columns", table_columns_path(@table) %>
  </p>

</div>

app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render "form", table: @table %>

<br>

<div>
  <%= link_to "Show this table", @table %> |
  <%= link_to "Back to tables", tables_path %>
</div>

app/views/tables/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tables</h1>

<div id="tables">
  <% @tables.each do |table| %>
    <%= render table %>
    <p>
      <%= link_to "Show this table", table %>
    </p>
  <% end %>
</div>

<%= link_to "New table", new_table_path %>

app/views/tables/new.html.erb
<h1>New table</h1>

<%= render "form", table: @table %>

<br>

<div>
  <%= link_to "Back to tables", tables_path %>
</div>

app/views/tables/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @table %>

<table>
  <tr>
    <%= render "row_header", columns: @table.columns %>
  </tr>

  <%= render @rows %>
</table>

<%= paginate @rows %>

<hr/>



<%= link_to "New column", new_table_column_path(@table) %>

<div>
  <%= link_to "Edit this table", edit_table_path(@table) %> |
  <%= link_to "Back to tables", tables_path %>

  <%= button_to "Destroy this table", @table, method: :delete %>
</div>