config/routes.rb
Rails.application.routes.draw do
  resources :select_options

  resources :tables do
    resources :columns
    resources :rows
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/row.rb
class Row < ApplicationRecord
  belongs_to :table
end

app/controllers/rows_controller.rb
class RowsController < ApplicationController
  before_action :set_table
  before_action :set_row, only: %i[ show edit update destroy ]

  # GET /rows or /rows.json
  def index
    @rows = Row.all
  end

  # GET /rows/1 or /rows/1.json
  def show
  end

  # GET /rows/new
  def new
    @row = @table.rows.new
  end

  # GET /rows/1/edit
  def edit
  end

  # POST /rows or /rows.json
  def create
    @row = @table.rows.new(row_params)

    respond_to do |format|
      if @row.save
        format.html { redirect_to table_rows_url(@table, @row), notice: "Row was successfully created." }
        format.json { render :show, status: :created, location: @row }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @row.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rows/1 or /rows/1.json
  def update
    respond_to do |format|
      updated_values = {}
      @table.columns.each do |column|
        case column.type
        when 'single_select'
          updated_values[column.code] = row_params[:values][column.code].to_i
        when 'single_line_text'
          updated_values[column.code] = row_params[:values][column.code]
        when 'date'
          updated_values[column.code] = row_params[:values][column.code]
        when 'number'
          updated_values[column.code] = row_params[:values][column.code].to_i
        when 'formula'
          # Do nothing
        end
      end
      puts updated_values
      puts row_params
      if @row.update_attribute :values, updated_values
        format.html { redirect_to table_url(@table), notice: "Row was successfully updated." }
        format.json { render :show, status: :ok, location: @row }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @row.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rows/1 or /rows/1.json
  def destroy
    @row.destroy

    respond_to do |format|
      format.html { redirect_to rows_url, notice: "Row was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_row
      @row = @table.rows.find(params[:id])
    end

    def set_table
      @table = Table.find(params[:table_id])
    end

    # Only allow a list of trusted parameters through.
    def row_params
      params.require(:row).permit(values: @table.columns.pluck(:code))
    end
end

app/helpers/rows_helper.rb
module RowsHelper
end

app/views/rows/_form.html.erb
<%= form_with(model: [@table, row]) do |form| %>
  <% if row.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(row.errors.count, "error") %> prohibited this row from being saved:</h2>

      <ul>
        <% row.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% @table.columns.each do |c|%>
  <div>
    <%= form.label c.name, style: "display: block" %>

    <% if c.type == "single_select" %>
      <%= select_tag "row[values[#{c.code}]]",  options_from_collection_for_select(c.select_options, "id", "text") %>
    <% else %>


    <%= text_field_tag "row[values[#{c.code}]]", row.values[c.code]%>
  </div>
  <% end %>

  <% end%>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rows/_row.html.erb
<tr id="<%= dom_id row %>">
  <td><%= link_to row.id, edit_table_row_path(@table, row) %></td>
  <% @table.columns.each do |c|%>
    <td>
    <% if c.type == "single_select" %>
      <%= @select_options_hash[row["values_#{c.code}"]] %>
    <% elsif c.type == "formula" %>
      <%= row["values_#{c.code}"]%>
    <% else %>
      <%= row["values_#{c.code}"]%>
    <% end %>
    </td>
  <% end %>

</tr>

app/views/rows/edit.html.erb
<h1>Editing row <%= @row.id %></h1>

<%= render "form", row: @row %>

<br>

<div>
  <%= link_to "Back to rows", table_rows_path(@table) %>
</div>

app/views/rows/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rows</h1>

<div id="rows">
  <% @rows.each do |row| %>
    <%= render row %>
    <p>
      <%= link_to "Show this row", row %>
    </p>
  <% end %>
</div>

<%= link_to "New row", new_row_path %>

app/views/rows/new.html.erb
<h1>New row</h1>

<%= render "form", row: @row %>

<br>

<div>
  <%= link_to "Back to rows", rows_path %>
</div>

app/views/rows/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @row %>

<div>
  <%= link_to "Edit this row", edit_row_path(@row) %> |
  <%= link_to "Back to rows", rows_path %>

  <%= button_to "Destroy this row", @row, method: :delete %>
</div>